// Generated by udon-ts. Do not edit by hand.
type int = number;
type uint = number;
type float = number;
type double = number;
type bool = boolean;
interface GameObject {}
interface Transform {}
interface Vector2 {}
interface Vector3 {}
interface Quaternion {}
interface Color {}
interface VRCPlayerApi {}
interface SerializationResult { readonly success: bool; readonly byteCount: int; }
interface DeserializationResult { readonly sendTime: float; readonly receiveTime: float; readonly isFromStorage: bool; }
interface UdonInputEventArgs { readonly boolValue: bool; readonly floatValue: float; }
declare enum VideoError { Unknown, InvalidURL, AccessDenied, PlayerError, RateLimited }
declare enum VRCInputMethod { Keyboard, Mouse, Controller, Gaze, Vive = 5, Oculus, Count }
interface ControllerColliderPlayerHit { readonly player: VRCPlayerApi; }
interface IVRCImageDownload {}
interface IVRCStringDownload {}
interface VRCAsyncGPUReadbackRequest {}
interface ScreenUpdateData {}
interface VRCCameraSettings {}
interface PlayerDataInfo { readonly key: string; readonly state: int; }
declare abstract class UdonBehaviour {
  readonly gameObject: GameObject;
  readonly transform: Transform;
  /** Behaviourが有効になったときに呼ばれます。 */
  OnEnable(): void;
  /** Behaviour開始時に一度呼ばれます。 */
  Start(): void;
  /** フレームごとに呼ばれます。 */
  Update(): void;
  /** Update後にフレームごとに呼ばれます。 */
  LateUpdate(): void;
  /** 物理更新ごとに呼ばれます。 */
  FixedUpdate(): void;
  /** IK計算後、フレーム終端付近で呼ばれます。 */
  PostLateUpdate(): void;
  /** Behaviourが無効になったときに呼ばれます。 */
  OnDisable(): void;
  /** ローカルプレイヤーがこのGameObjectを操作したときに呼ばれます。 */
  Interact(): void;
  /** ローカルプレイヤーがこのオブジェクトを拾ったときに呼ばれます。 */
  OnPickup(): void;
  /** ローカルプレイヤーがこのオブジェクトを離したときに呼ばれます。 */
  OnDrop(): void;
  /** Pickup使用ボタンを押したときに呼ばれます。 */
  OnPickupUseDown(): void;
  /** Pickup使用ボタンを離したときに呼ばれます。 */
  OnPickupUseUp(): void;
  /** プレイヤーがインスタンスへ参加したときに呼ばれます。 */
  OnPlayerJoined(player: VRCPlayerApi): void;
  /** プレイヤーがインスタンスから退出したときに呼ばれます。 */
  OnPlayerLeft(player: VRCPlayerApi): void;
  /** プレイヤーの永続データ読み込み完了後に呼ばれます。 */
  OnPlayerRestored(player: VRCPlayerApi): void;
  /** ローカルプレイヤーがリスポーンしたときに呼ばれます。 */
  OnPlayerRespawn(player: VRCPlayerApi): void;
  /** プレイヤーのsuspend状態が変化したときに呼ばれます。 */
  OnPlayerSuspendChanged(player: VRCPlayerApi): void;
  /** プレイヤーのAvatar読み込み完了時に呼ばれます。 */
  OnAvatarChanged(player: VRCPlayerApi): void;
  /** プレイヤーのAvatar眼高が変化したときに呼ばれます。 */
  OnAvatarEyeHeightChanged(player: VRCPlayerApi, previousEyeHeight: float): void;
  /** プレイヤーがTriggerへ入ったときに呼ばれます。 */
  OnPlayerTriggerEnter(player: VRCPlayerApi): void;
  /** プレイヤーがTrigger内にいる間、毎フレーム呼ばれます。 */
  OnPlayerTriggerStay(player: VRCPlayerApi): void;
  /** プレイヤーがTriggerから出たときに呼ばれます。 */
  OnPlayerTriggerExit(player: VRCPlayerApi): void;
  /** プレイヤーがColliderへ入ったときに呼ばれます。 */
  OnPlayerCollisionEnter(player: VRCPlayerApi): void;
  /** プレイヤーがCollider内にいる間、毎フレーム呼ばれます。 */
  OnPlayerCollisionStay(player: VRCPlayerApi): void;
  /** プレイヤーがColliderから出たときに呼ばれます。 */
  OnPlayerCollisionExit(player: VRCPlayerApi): void;
  /** Particleがプレイヤーへ衝突したときに呼ばれます。 */
  OnPlayerParticleCollision(player: VRCPlayerApi): void;
  /** CharacterControllerがプレイヤーへ衝突したときに呼ばれます。 */
  OnControllerColliderHitPlayer(hit: ControllerColliderPlayerHit): void;
  /** ローカルプレイヤーがStationへ入ったときに呼ばれます。 */
  OnStationEntered(player: VRCPlayerApi): void;
  /** ローカルプレイヤーがStationから出たときに呼ばれます。 */
  OnStationExited(player: VRCPlayerApi): void;
  /** 所有権移譲要求を受けたときに呼ばれます。trueを返すと許可します。 */
  OnOwnershipRequest(requestingPlayer: VRCPlayerApi, requestedOwner: VRCPlayerApi): boolean;
  /** オブジェクトの所有者が変化したときに呼ばれます。 */
  OnOwnershipTransferred(player: VRCPlayerApi): void;
  /** インスタンスマスターが変化したときに呼ばれます。 */
  OnMasterTransferred(player: VRCPlayerApi): void;
  /** 同期変数をシリアライズする直前に呼ばれます。 */
  OnPreSerialization(): void;
  /** 同期変数の送信試行後に呼ばれます。 */
  OnPostSerialization(result: SerializationResult): void;
  /** 同期変数を受信したとき、時刻情報とともに呼ばれます。 */
  OnDeserialization(result?: DeserializationResult): void;
  /** Object Poolからspawnされたときに呼ばれる非推奨イベントです。 */
  OnSpawn(): void;
  /** Video Playerが動画を読み込んだときに呼ばれます。 */
  OnVideoReady(): void;
  /** Video Playerが停止状態から再生を開始したときに呼ばれます。 */
  OnVideoStart(): void;
  /** Video Playerが再生を開始したときに呼ばれます。 */
  OnVideoPlay(): void;
  /** Video Playerが一時停止したときに呼ばれます。 */
  OnVideoPause(): void;
  /** Video Playerがループ末尾へ到達したときに呼ばれます。 */
  OnVideoLoop(): void;
  /** Video Playerの再生が終了したときに呼ばれます。 */
  OnVideoEnd(): void;
  /** Video Playerでエラーが起きたときに呼ばれます。 */
  OnVideoError(videoError: VideoError): void;
  /** 画像の読み込みに成功したときに呼ばれます。 */
  OnImageLoadSuccess(result: IVRCImageDownload): void;
  /** 画像の読み込みに失敗したときに呼ばれます。 */
  OnImageLoadError(result: IVRCImageDownload): void;
  /** 文字列の読み込みに成功したときに呼ばれます。 */
  OnStringLoadSuccess(result: IVRCStringDownload): void;
  /** 文字列の読み込みに失敗したときに呼ばれます。 */
  OnStringLoadError(result: IVRCStringDownload): void;
  /** 非同期GPU readback完了時に呼ばれます。 */
  OnAsyncGpuReadbackComplete(request: VRCAsyncGPUReadbackRequest): void;
  /** Jump入力時に呼ばれます。 */
  InputJump(value: boolean, args: UdonInputEventArgs): void;
  /** Use入力時に呼ばれます。 */
  InputUse(value: boolean, args: UdonInputEventArgs): void;
  /** Grab入力時に呼ばれます。 */
  InputGrab(value: boolean, args: UdonInputEventArgs): void;
  /** Drop入力時に呼ばれます。 */
  InputDrop(value: boolean, args: UdonInputEventArgs): void;
  /** 水平移動入力時に呼ばれます。 */
  InputMoveHorizontal(value: float, args: UdonInputEventArgs): void;
  /** 垂直移動入力時に呼ばれます。 */
  InputMoveVertical(value: float, args: UdonInputEventArgs): void;
  /** 水平視点入力時に呼ばれます。 */
  InputLookHorizontal(value: float, args: UdonInputEventArgs): void;
  /** 垂直視点入力時に呼ばれます。 */
  InputLookVertical(value: float, args: UdonInputEventArgs): void;
  /** MIDI Note On受信時に呼ばれます。 */
  MidiNoteOn(channel: int, number: int, velocity: int): void;
  /** MIDI Note Off受信時に呼ばれます。 */
  MidiNoteOff(channel: int, number: int, velocity: int): void;
  /** MIDI Control Change受信時に呼ばれます。 */
  MidiControlChange(channel: int, number: int, value: int): void;
  /** 永続ストレージ使用量が更新されたときに呼ばれます。 */
  OnPersistenceUsageUpdated(player: VRCPlayerApi): void;
  /** Player Data容量を超えたときに呼ばれます。 */
  OnPlayerDataStorageExceeded(player: VRCPlayerApi): void;
  /** Player Data容量上限へ近づいたときに呼ばれます。 */
  OnPlayerDataStorageWarning(player: VRCPlayerApi): void;
  /** Player Object容量を超えたときに呼ばれます。 */
  OnPlayerObjectStorageExceeded(player: VRCPlayerApi): void;
  /** Player Object容量上限へ近づいたときに呼ばれます。 */
  OnPlayerObjectStorageWarning(player: VRCPlayerApi): void;
  /** Player Dataが更新または受信されたフレーム終端で呼ばれます。 */
  OnPlayerDataUpdated(player: VRCPlayerApi, infos: PlayerDataInfo[]): void;
  /** モバイル画面状態が更新されたときに呼ばれます。 */
  OnScreenUpdate(data: ScreenUpdateData): void;
  /** 入力デバイス方式が変わったときに呼ばれます。 */
  OnInputMethodChanged(inputMethod: VRCInputMethod): void;
  /** 表示言語が変わったときに呼ばれます。 */
  OnLanguageChanged(language: string): void;
  /** Gift Dropが発生したときに呼ばれます。 */
  OnVRCPlusMassGift(gifter: VRCPlayerApi, numGifts: int): void;
  /** VRChat Camera設定が変化したときに呼ばれます。 */
  OnVRCCameraSettingsChanged(camera: VRCCameraSettings): void;
  /** VRChat Graphics品質設定が変化したときに呼ばれます。 */
  OnVRCQualitySettingsChanged(): void;
}

declare namespace Debug {
  function log(arg0: unknown): void;
  function Log(arg0: unknown): void;
  function logWarning(arg0: unknown): void;
  function LogWarning(arg0: unknown): void;
  function logError(arg0: unknown): void;
  function LogError(arg0: unknown): void;
}

declare namespace Mathf {
  function sin(arg0: float): float;
  function Sin(arg0: float): float;
  function cos(arg0: float): float;
  function Cos(arg0: float): float;
  function clamp(arg0: float, arg1: float, arg2: float): float;
  function Clamp(arg0: float, arg1: float, arg2: float): float;
}

declare namespace Networking {
  const localPlayer: VRCPlayerApi;
}

declare namespace Time {
  const deltaTime: float;
  const time: float;
}

interface GameObject {
  setActive(arg0: boolean): void;
  SetActive(arg0: boolean): void;
}

interface VRCPlayerApi {
  readonly displayName: string;
  setWalkSpeed(arg0: float): void;
  SetWalkSpeed(arg0: float): void;
  setRunSpeed(arg0: float): void;
  SetRunSpeed(arg0: float): void;
  setJumpImpulse(arg0: float): void;
  SetJumpImpulse(arg0: float): void;
}

declare function extern<T = void>(signature: string, ...args: unknown[]): T;
