import { staticSourceName } from "./extern-registry.js";
import { events } from "./events.js";
import type { ExternDefinition, ExternParameter, UdonType } from "./model.js";
import { sourceTypeName } from "./type-system.js";

function declarationType(type: UdonType): string {
  if (type === "SystemVoid") return "void";
  if (type === "SystemObject") return "unknown";
  return sourceTypeName(type);
}

function parameters(parameters: readonly ExternParameter[]): string {
  return parameters.map((parameter, index) => {
    const mode = parameter.mode && parameter.mode !== "in" ? `/** ${parameter.mode} */ ` : "";
    return `${mode}arg${index}: ${declarationType(parameter.type)}`;
  }).join(", ");
}

function memberLines(definition: ExternDefinition, indent: string): string[] {
  const names = [definition.member, ...(definition.aliases ?? [])];
  return names.map((name) => {
    if (definition.kind === "get") return `${indent}readonly ${name}: ${declarationType(definition.returns)};`;
    if (definition.kind === "set") return `${indent}${name}: ${declarationType(definition.parameters[0]?.type ?? "SystemObject")};`;
    return `${indent}${name}(${parameters(definition.parameters)}): ${declarationType(definition.returns)};`;
  });
}

function eventMethodName(sourceName: string): string {
  return sourceName.length === 0 ? sourceName : sourceName[0]!.toUpperCase() + sourceName.slice(1);
}

function eventMethodLines(): string[] {
  const groups = new Map<string, Array<(typeof events)[number]>>();
  for (const definition of events) {
    const values = groups.get(definition.sourceName) ?? [];
    values.push(definition);
    groups.set(definition.sourceName, values);
  }
  const lines: string[] = [];
  for (const [sourceName, definitions] of groups) {
    const zeroArgument = definitions.find((definition) => definition.parameters.length === 0);
    const oneArgument = definitions.find((definition) => definition.parameters.length === 1);
    const variants = zeroArgument && oneArgument && definitions.length === 2
      ? [{
          ...oneArgument,
          parameters: [{ ...oneArgument.parameters[0]!, name: `${oneArgument.parameters[0]!.name}?` }]
        }]
      : definitions;
    for (const definition of variants) {
      if (definition.description) lines.push(`  /** ${definition.description} */`);
      const args = definition.parameters
        .map((eventParameter) => `${eventParameter.name}: ${declarationType(eventParameter.type)}`)
        .join(", ");
      lines.push(`  ${eventMethodName(sourceName)}(${args}): ${declarationType(definition.returns ?? "SystemVoid")};`);
    }
  }
  return lines;
}

function eventRegistrationLines(): string[] {
  const lines: string[] = [];
  for (const definition of events) {
    const args = definition.parameters
      .map((eventParameter) => `${eventParameter.name}: ${declarationType(eventParameter.type)}`)
      .join(", ");
    const returns = declarationType(definition.returns ?? "SystemVoid");
    lines.push(`declare function on(event: "${eventMethodName(definition.sourceName)}", handler: (${args}) => ${returns}): void;`);
  }
  lines.push(
    "declare function on(event: string, handler: () => void): void;",
    "declare function emit(event: string): void;",
    "declare function emitDelayed(event: string, seconds: float): void;",
    "declare function emitDelayedFrames(event: string, frames: int): void;",
    "declare function emitNetwork(target: NetworkEventTarget, event: string): void;"
  );
  return lines;
}

/** Generates editor declarations from the same extern registry used by the compiler. */
export function generateDeclarations(definitions: readonly ExternDefinition[]): string {
  const staticGroups = new Map<string, ExternDefinition[]>();
  const instanceGroups = new Map<string, ExternDefinition[]>();
  const udonGroups = new Map<string, ExternDefinition[]>();
  const udonStaticGroups = new Map<string, ExternDefinition[]>();

  for (const definition of definitions) {
    const staticName = definition.static ? staticSourceName(definition.owner) : undefined;
    if (staticName) {
      const values = staticGroups.get(staticName) ?? [];
      values.push(definition);
      staticGroups.set(staticName, values);
      continue;
    }
    if (definition.static) {
      const values = udonStaticGroups.get(definition.owner) ?? [];
      values.push(definition);
      udonStaticGroups.set(definition.owner, values);
      continue;
    }
    const sourceName = sourceTypeName(definition.owner);
    if (sourceName.startsWith("Udon.")) {
      const groups = definition.static ? udonStaticGroups : udonGroups;
      const values = groups.get(sourceName.slice(5)) ?? [];
      values.push(definition);
      groups.set(sourceName.slice(5), values);
    } else {
      const values = instanceGroups.get(sourceName) ?? [];
      values.push(definition);
      instanceGroups.set(sourceName, values);
    }
  }

  const lines = [
    "// Generated by udon-ts. Do not edit by hand.",
    "type int = number;",
    "type uint = number;",
    "type float = number;",
    "type double = number;",
    "type bool = boolean;",
    "interface GameObject {}",
    "interface Transform {}",
    "interface Vector2 {}",
    "interface Vector3 {}",
    "interface Quaternion {}",
    "interface Color {}",
    "interface VRCPlayerApi {}",
    "interface SerializationResult { readonly success: bool; readonly byteCount: int; }",
    "interface DeserializationResult { readonly sendTime: float; readonly receiveTime: float; readonly isFromStorage: bool; }",
    "interface UdonInputEventArgs { readonly boolValue: bool; readonly floatValue: float; }",
    "declare enum VideoError { Unknown, InvalidURL, AccessDenied, PlayerError, RateLimited }",
    "declare enum VRCInputMethod { Keyboard, Mouse, Controller, Gaze, Vive = 5, Oculus, Count }",
    "declare enum NetworkEventTarget { All, Owner, Others, Self }",
    "interface ControllerColliderPlayerHit { readonly player: VRCPlayerApi; }",
    "interface IVRCImageDownload {}",
    "interface IVRCStringDownload {}",
    "interface VRCAsyncGPUReadbackRequest {}",
    "interface ScreenUpdateData {}",
    "interface VRCCameraSettings {}",
    "interface PlayerDataInfo { readonly key: string; readonly state: int; }",
    "interface UdonVariableOptions { readonly sync?: \"none\" | \"linear\" | \"smooth\"; }",
    "type UdonVariableDecorator = <This, Value>(value: undefined, context: ClassFieldDecoratorContext<This, Value>) => void;",
    "declare function udonVariable<This, Value>(value: undefined, context: ClassFieldDecoratorContext<This, Value>): void;",
    "declare function udonVariable(options: UdonVariableOptions): UdonVariableDecorator;",
    "declare function udonVariable<T>(initialValue?: T, options?: UdonVariableOptions): T;",
    ...eventRegistrationLines(),
    "declare abstract class UdonBehaviour {",
    "  readonly gameObject: GameObject;",
    "  readonly transform: Transform;",
    ...eventMethodLines(),
    "}",
    ""
  ];

  for (const [name, group] of [...staticGroups].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`declare namespace ${name} {`);
    for (const definition of group) {
      if (definition.kind === "get") {
        for (const member of [definition.member, ...(definition.aliases ?? [])]) {
          lines.push(`  const ${member}: ${declarationType(definition.returns)};`);
        }
      } else {
        lines.push(...memberLines(definition, "  ").map((line) => `  function ${line.trimStart()}`));
      }
    }
    lines.push("}", "");
  }
  for (const [name, group] of [...instanceGroups].sort(([a], [b]) => a.localeCompare(b))) {
    lines.push(`interface ${name} {`);
    for (const definition of group) lines.push(...memberLines(definition, "  "));
    lines.push("}", "");
  }
  if (udonGroups.size > 0 || udonStaticGroups.size > 0) {
    lines.push("declare namespace Udon {");
    for (const [name, group] of [...udonStaticGroups].sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`  namespace ${name} {`);
      for (const definition of group) {
        if (definition.kind === "get") {
          for (const member of [definition.member, ...(definition.aliases ?? [])]) {
            lines.push(`    const ${member}: ${declarationType(definition.returns)};`);
          }
        } else {
          lines.push(...memberLines(definition, "    ").map((line) => `    function ${line.trimStart()}`));
        }
      }
      lines.push("  }");
    }
    for (const [name, group] of [...udonGroups].sort(([a], [b]) => a.localeCompare(b))) {
      lines.push(`  interface ${name} {`);
      for (const definition of group) lines.push(...memberLines(definition, "    "));
      lines.push("  }");
    }
    lines.push("}", "");
  }
  lines.push("declare function extern<T = void>(signature: string, ...args: unknown[]): T;", "");
  return lines.join("\n");
}
